export enum PermissionCodes {
  Admin = "ADMIN",
  UsersRead = "USER_R",
  AreaCreate = "AREA_C",
  AreaUpdate = "AREA_U",
  AreaDelete = "AREA_D",
  RoleCreate = "ROLE_C",
  RoleUpdate = "ROLE_U",
  RoleDelete = "ROLE_D",
  AdminArea = "ADMIN_AREA",
  PatientRead = "PATIENT_R",
  PatientCreate = "PATIENT_C",
  PatientUpdate = "PATIENT_U",
  TreatmentCreate = "TREATMENT_C",
  TreatmentRead = "TREATMENT_R",
  TreatmentUpdate = "TREATMENT_U",
  TreatmentDelete = "TREATMENT_D",
}
