export enum PermissionCodes {
  Admin = "ADMIN",
  UsersRead = "USER_R",
  AreaCreate = "AREA_C",
  AreaUpdate = "AREA_U",
  AreaDelete = "AREA_D",
  RoleCreate = "ROLE_C",
  RoleUpdate = "ROLE_U",
  RoleDelete = "ROLE_D",
  RoleUserCreate = "ROLEUSER_C",
  RoleUserDelete = "ROLEUSER_D",
  AdminRole = "ADMIN_ROLE",
  AdminArea = "ADMIN_AREA",
  PatientRead = "PATIENT_R",
  PatientCreate = "PATIENT_C",
  PatientUpdate = "PATIENT_U",
  ProfessionalRead = "PROFESSIONAL_R",
  ProfessionalCreate = "PROFESSIONAL_C",
  ProfessionalUpdate = "PROFESSIONAL_U",
}
