export enum PermissionCodes {
  Admin = "ADMIN",
  UsersRead = "USER_R",
  AreaCreate = "AREA_C",
  AreaUpdate = "AREA_U",
  AreaDelete = "AREA_D",
  RoleCreate = "ROLE_C",
  RoleUpdate = "ROLE_U",
  RoleDelete = "ROLE_D",
  AdminRole = "ADMIN_ROLE",
  AdminArea = "ADMIN_AREA",
  PatientRead = "PATIENT_R",
  PatientCreate = "PATIENT_C",
  PatientUpdate = "PATIENT_U",
  DocumentationRead = "DOCUMENTATION_R",
  DocumentationCreate = "DOCUMENTATION_C",
}
